# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit of a mixture of gaussians and one uniform using EM
#'
#' This program performs the EM update for a mixture of different gaussians and
#' one uniform distribution. The width of the uniform if not specified is
#' computed from the data. The number of gaussians in the mixture is determined
#' by the length of the parameter \code{mu_}.
#'
#' @param y_ The data to be fit with the mixture. It must be a matrix where each
#'   column is a variable and each row is a dimension.
#' @param mu_ Vector giving the initial values for the means of the gaussians.
#'   Its length determines the number of gaussians to be included in the
#'   mixture.
#' @param w_ Vector giving the initial wights of the gaussians and the uniform.
#'   It must sum to 1.
#' @param list_sigma_ List of matrices each giving the starting covariance
#'   matrix for each gaussians.
#' @param delta_ Dimensions of the uniform distribution. If it's 0 then the
#'   dimensions are the difference between the maximum and the minum of the data
#'   in each direction.
#' @param verbose_ Should some information be printed?
#'
#' @return A list containing the fitted statistics of the mixture and a matrix
#'   containing the posterior probability for each point to come from each
#'   component of the mixture (one column is one component, one row is one data
#'   point).
#'
#' @export
EM_Luca <- function(y_, mu_, w_, list_sigma_, delta_, verbose_) {
    .Call('vngFCM_EM_Luca', PACKAGE = 'vngFCM', y_, mu_, w_, list_sigma_, delta_, verbose_)
}

