// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// EM_Luca
SEXP EM_Luca(SEXP y_, SEXP mu_, SEXP w_, SEXP list_sigma_, SEXP delta_, SEXP verbose_);
RcppExport SEXP vngFCM_EM_Luca(SEXP y_SEXP, SEXP mu_SEXP, SEXP w_SEXP, SEXP list_sigma_SEXP, SEXP delta_SEXP, SEXP verbose_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type mu_(mu_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type w_(w_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_sigma_(list_sigma_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type delta_(delta_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type verbose_(verbose_SEXP);
    __result = Rcpp::wrap(EM_Luca(y_, mu_, w_, list_sigma_, delta_, verbose_));
    return __result;
END_RCPP
}
